# Generated by Django 4.0.3 on 2022-04-05 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEPARTMENT',
            fields=[
                ('DepartmentNo', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=255)),
                ('ManagerID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LOGIN',
            fields=[
                ('UserUsername', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='DNo',
            field=models.ForeignKey(default='NULL', null=True, on_delete=django.db.models.deletion.CASCADE, to='API.department'),
        ),
    ]
