# Generated by Django 4.0.3 on 2022-04-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_department_login_alter_user_dno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserUsername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.login'),
        ),
        migrations.CreateModel(
            name='MANAGER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ManagerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
    ]
