# Generated by Django 4.0.3 on 2022-04-06 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_user_userusername_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='ManagerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.manager'),
        ),
    ]
