# Generated by Django 4.0.3 on 2022-04-06 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_department_managerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DNo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.department'),
        ),
        migrations.CreateModel(
            name='SCHEDULE',
            fields=[
                ('ScheduleID', models.AutoField(primary_key=True, serialize=False)),
                ('CreatorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.manager')),
            ],
        ),
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
                ('EmpScheduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.schedule')),
            ],
        ),
    ]
