# Generated by Django 4.0.3 on 2022-04-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_remove_employee_id_alter_employee_empid_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.user'),
        ),
    ]
