# Generated by Django 4.0.3 on 2022-04-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_employee_empid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TIME_LOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Date', models.DateField()),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='time_log',
            constraint=models.UniqueConstraint(fields=('EmpID', 'StartTime'), name='Time_log_pk'),
        ),
    ]
