# Generated by Django 4.0.3 on 2022-04-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_time_log_time_log_time_log_pk'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='time_log',
            name='Time_log_pk',
        ),
        migrations.AddConstraint(
            model_name='time_log',
            constraint=models.UniqueConstraint(fields=('EmpID', 'StartTime'), name='Time_log_pk'),
        ),
    ]
