# Generated by Django 4.0.3 on 2022-04-06 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_remove_time_log_time_log_pk_time_log_time_log_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='INVOICE',
            fields=[
                ('InvoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='time_log',
            name='Time_log_pk',
        ),
        migrations.AddConstraint(
            model_name='time_log',
            constraint=models.UniqueConstraint(fields=('EmpID', 'StartTime'), name='TimeLogPK'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='InvoiceDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.time_log'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='InvoiceEmpID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employee'),
        ),
    ]
