# Generated by Django 4.0.3 on 2022-04-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_invoice_remove_time_log_time_log_pk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROJECT',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=255, unique=True)),
                ('ContrllingDepartmentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.department')),
            ],
        ),
        migrations.CreateModel(
            name='WORKS_ON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employee')),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='works_on',
            constraint=models.UniqueConstraint(fields=('EmpID', 'ProjectID'), name='WorksOnPK'),
        ),
    ]
