# Generated by Django 4.0.3 on 2022-04-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_project_works_on_works_on_worksonpk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
