# Generated by Django 4.0.3 on 2022-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_user_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_shifts',
            name='Time',
        ),
        migrations.AddField(
            model_name='schedule_shifts',
            name='EndTime',
            field=models.TimeField(default='23:00:00'),
        ),
        migrations.AddField(
            model_name='schedule_shifts',
            name='StartTime',
            field=models.TimeField(default='22:00:00'),
        ),
    ]
