# Generated by Django 4.0.3 on 2022-04-12 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_employee_salary_employee_my_float_constraint'),
        ('API', '0017_employee_salary_alter_time_log_endtime_and_more'),
    ]

    operations = [
    ]
