# Generated by Django 4.0.3 on 2022-04-14 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_merge_20220412_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserUsername',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.login'),
        ),
    ]
