# Generated by Django 4.0.3 on 2022-04-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_alter_login_password_alter_user_userusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserUsername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.login', unique=True),
        ),
    ]
