# Generated by Django 4.0.3 on 2022-04-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_alter_user_userusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='eid', serialize=False, to='API.user'),
        ),
    ]
